LOAD DATA LOCAL INFILE 'items.txt' INTO TABLE Items
FIELDS TERMINATED BY '|+_=|';

LOAD DATA LOCAL INFILE 'category.txt' INTO TABLE Category
FIELDS TERMINATED BY '|+_=|';

LOAD DATA LOCAL INFILE 'bids.txt' INTO TABLE Bids
FIELDS TERMINATED BY '|+_=|';

LOAD DATA LOCAL INFILE 'bidder.txt' INTO TABLE Bidder
FIELDS TERMINATED BY '|+_=|';

LOAD DATA LOCAL INFILE 'seller.txt' INTO TABLE Seller
FIELDS TERMINATED BY '|+_=|'; 

